services:
    PoP\CustomPosts\FieldResolvers\:
        resource: '../src/FieldResolvers/*'
        public: true

    PoP\CustomPosts\TypeResolvers\:
        resource: '../src/TypeResolvers/*'
        public: true

    PoP\CustomPosts\FieldInterfaceResolvers\:
        resource: '../src/FieldInterfaceResolvers/*'
        public: true
